#+TITLE:       贝叶斯攻击图与网络安全态势
#+AUTHOR:      Pinvon
#+EMAIL:       pinvon@Inspiron
#+DATE:        2017-12-30 六
#+URI:         /blog/%y/%m/%d/贝叶斯攻击图与网络安全态势
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        每日论文
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

* 攻击行为预测

** 攻击图

攻击图模型目前是网络安全风险评估中，用于表达网络或信息系统中存在的脆弱点，以及脆弱点之间的关联关系的最有效的模型之一。攻击图以有向图的方式来表达攻击者利用存在的脆弱性对网络或信息系统进行攻击的所有可能的攻击路径，全面地反映了网络或信息系统中脆弱点利用之间的依赖关系。

*** 攻击图生成

工具：MulVAL

*** 攻击图分析方法

攻击图表示了被评估的网络或信息系统中存在的脆弱点以及攻击者利用这些脆弱点进行一步或多步攻击的各种可能的攻击路径。学术界对攻击图的自动化生成方法进行了充分的研究，并且得到了有效的研究成果和实际应用的工具，使得攻击图的生成复杂度以及攻击图的规模能够控制在 $O(n^2)$ 之内，因此，攻击图模型相对其他脆弱性评估模型而言，有巨大的优势。

网络安全态势预测中，一个重要的指标是攻击发生的可能性大小，即攻击概率。攻击概率反映了网络的安全状况，并预测将会发生的攻击及其可能性大小，这是后续安全态势计算的基础。

状态攻击图存在状态爆炸问题，无法适用于大规模网络。而属性攻击图则避免了状态爆炸现象。

大部分论文，都是通过对网络或信息系统中的脆弱点利用的不确定性以及脆弱点利用的关联性来计算攻击概率（或类似的指标），但忽略了网络或信息系统中资产分布和威胁分布状况等重要环境因素对攻击发生可能性的影响[fn:1]。

** 攻击图转贝叶斯网

属性攻击图是一种有向无环图，它含有2种节点：属性节点和原子攻击节点。而贝叶斯网络是一个有向无环图，具有因果关系和概率主义，可以根据已知的信息对未知的结果或原因进行推理和预测。在贝叶斯网络中，节点的状态及发生概率只与父节点有关，在攻击图中网络脆弱点是否被利用也只与攻击路径中的父节点有关，这种节点关系在贝叶斯网络和攻击图中相对应。由于贝叶斯网络和攻击图都是一种有向无环图，并且有向边表示一种因果关系，因此可以将贝叶斯网络和攻击图进行结合，对网络安全态势进行预测[fn:2]。

*** 贝叶斯网与网络安全态势感知

由于基于贝叶斯网络的方法能够充分利用攻击图的结构和脆弱点利用复杂度等信息，从而不需要对结构和参数进行学习，加上贝叶斯网络在概率逻辑关系推理方面的优势，使其适用于网络安全态势感知。

**** 现有的方法

Xie等人[fn:3]在攻击图的基础上构建贝叶斯网络，然后建立报警节点作为证据节点；Poolsappasit等人[fn:4]也是在攻击图的基础上构建贝叶斯网络，然后根据警报将相应的原子攻击节点设为证据节点。每个节点的攻击发生概率是这些证据的后验概率。

缺点：需要对所有节点建立条件概率表，需要较多的先验知识，在实时性上性能不同。

* 网络安全态势感知

** 网络攻击建模

对于攻击者来说，发动一次攻击可能需要具备一些前提条件，而攻击成功后，往往又会获得一些新的后置条件。

*** 定义

1. 攻击条件 $S$ 

攻击条件指的是访问权限、网络连通性、系统状态、网络状态等攻击者可以获得或利用的网络或信息系统属性。

2. 原子攻击 $A(S_{pre}, S_{post})$

原子攻击指的是攻击者的一次基本攻击，对应于一次脆弱点利用。对于每一个原子攻击 $a \in A$ ，只有满足其前提条件集合 $S_{pre}$ ，才可能成功发动该原子攻击。而当该原子攻击成功发生之后，攻击者将会获得其后置条件集合 $S_{post}$ 。

3. 攻击难度 $D(a)$

在实际情况中，不能脆弱点的利用难度是不同的。有些脆弱点的利用不需要借助其他额外条件，而有些则必须依赖其他行为。CVSS给出了脆弱点的攻击难度度量的依据。

4. 资产 $H$

资产是网络中存在价值的信息和资源，是网络中需要保护的对象。包括网络中的硬件、软件、文档、数据等。

在分析攻击概率的时候，不能忽略资产对攻击发生可能性的影响。为了分析资产的价值和重要度对攻击发生可能性的影响，定义了攻击收益的概念。

5. 攻击收益 $G$ 

资产被成功攻击后攻击者获得的收益的度量指标。

6. 攻击成功概率 $P$

*** 建模

$BAG=(S, A, E, P)$

* Footnotes

[fn:4] Poolsappasit N, Dewri R, Ray I. Dynamic security risk management using bayesian attack graphs[J]. IEEE Transactions on Dependable and Secure Computing, 2012, 9(1): 61-74.

[fn:3] Xie P, Li J H, Ou X, et al. Using Bayesian networks for cyber security analysis[C]//Dependable Systems and Networks (DSN), 2010 IEEE/IFIP International Conference on. IEEE, 2010: 211-220.

[fn:1] 吴金宇. 网络安全风险评估关键技术研究[D]. 北京邮电大学, 2013.

[fn:2] 王秀娟, 孙博, 廖彦文, 等. 贝叶斯属性攻击图网络脆弱性评估[J]. 2015.
