#+TITLE:       Beamer
#+AUTHOR:      Pinvon
#+EMAIL:       pinvon@Inspiron
#+DATE:        2018-06-29 五

#+URI:         /blog/Latex/%y/%m/%d/%t/ Or /blog/Latex/%t/
#+TAGS:        Latex
#+DESCRIPTION: <Add description here>

#+LANGUAGE:    en
#+OPTIONS:     H:4 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

* 概述

Beamer 是基于 Latex 的, 可以使用 Beamer 来写幻灯片, 讲义等.

* 基本代码

#+BEGIN_SRC Latex
\documentclass[slidestop,compress,mathserif]{beamer}
\usepackage{ctex}
\usetheme{Antibes}
\usecolortheme{lily}

\title{汇报}
\author{Pinvon}

\begin{document}

\section{概述}

\subsection{历史}  % 一页

blabla

\begin{frame}  % 一页
  \frametitle{中国历史}
  阐述自己的建议和意见, 如何规划, 实施计划等.
\end{frame}

\begin{frame}  % 一页
  \frametitle{总结}
  个人的学期总结报告, 暑期计划等.
\end{frame}

\subsection{国情}

\begin{frame}  % 一页
  \frametitle{制定}
  制定自己的任务, 目标, 完成的奖惩办法.
\end{frame}
\end{document}
#+END_SRC

section: 如果有内容, 会占一页, 这边无内容, 直接跳过.

subsection: 如果有内容, 会占一页, 如这边有 blabla.

frame: 每一个 frame 就是一页. 一个 section 里面可以包含多个 frame.

** 主题

Beamer v3.0 中的主题有以下几种:
- W/o 导航条: default, boxes, Bergen, Madrid, Pittsburgh, Rochester
- 带树形导航条: Antibes(例子中使用的主题), JuanLesPins, Montpellier
- 带目录的侧边导航条: Berkeley, PaloAlto, Goettingen, Marburg, Hannover
- 带微型 frame 导航条: Berlin, Ilmenau, Dresden, Darmstadt, Frankfurt, Singapore, Szeged
- 带节小节标题: Copenhagen, Luebeck, Malmoe, Warsaw

** 版面设计

[slidestop]: 将页面标题放在左上角, 默认是 [slidescentered]

[compress]: 尽可能压小所有导航条, 默认是 [uncompressed]

[red]: 导航条和标题为淡红色, 也可以改成 blue, brown 等其他颜色

** frame 选项

[shrink]: 适用于缩小内容充满一张幻灯片

* 字体

数学字体: [mathsans/mathserif]

* 颜色

- 单一背景色: \beamersetaveragebackground{color}, \beamertemplatesolidbackgroundcolor{color}
- 渐变色: \beamertemplateshadingbackground{color1}{color2}
- 栅格背景: \beamertemplategridbackground[grid_space]

* 图形

可以使用 Latex 中使用的引入图形的方式.


