#+TITLE:       Ubuntu 常见问题
#+AUTHOR:      Pinvon
#+EMAIL:       pinvon@Inspiron
#+DATE:        2018-04-09 一
#+URI:         /blog/%y/%m/%d/ubuntu-常见问题
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        OS
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

* 安装 Ubuntu 时手动划分分区

在安装类型中选择"其他选项(您可以自己创建, 调整分区, 或者为 Ubuntu Kylin)选择多个分区".

** 硬盘名称

可以看到有 /dev/sda, /dev/sda1, /dev/sda5, /dev/sda6, 空闲 等类似字眼.

其中, /dev/sda1, /dev/sda5, /dev/sda6 这些都属于 /dev/sda, 表示 Linux 下的磁盘分区名称. /dev/后面的字母的意思如下:
- 第一个字母: s 或 h, s 表示 SATA 或 SCSI 接口的硬盘, h 表示 IDE 接口的硬盘.
- 第二个字母: d, 即 derive, 表示磁盘驱动器.
- 第三个字母: a, b, c, d, 等等, 表示顺序.

所以, sda 是指 SATA 或 SCSI 接口的硬盘的第一块硬盘, 第二块可以表示为 sdb, 依此类推. 然后, sda1 是指第一块硬盘的第一个分区. 而 sda1 是指第一块硬盘的第一个分区, sda5 是指第一块硬盘的第五个分区, 依此类推.

** 分区类型

*** 主分区

一个硬盘的主分区包含操作系统启动所必需的文件和数据的硬盘分区. 要在硬盘上安装操作系统, 则硬盘必须有一个主分区. 主分区中不能再划分其他类型的分区, 每个主分区都相当于一个逻辑磁盘.

每个硬盘最多可以有 4 个主分区, 每个主分区可以有各自独立的引导块, 可以用 fdisk 设定为启动区. 比如装双系统, 就需要两个主分区.

*** 扩展分区

在一个硬盘里, 除了主分区, 剩下的都是扩展分区. 扩展分区不能直接使用, 需要划分成若干个逻辑分区才能使用.

*** 逻辑分区

逻辑分区是硬盘上一块连接的区块. 每个逻辑分区对应一个逻辑驱动器, 这些逻辑驱动器没有独立的引导块, 不能用 fdisk 设定为启动区.

** 空闲分区

空闲分区就是我们可以操作的分区. 双击就可以进行分区划分了.

** 划分分区

*** SWAP 分区

这个分区的意思是虚拟内存, 既然是虚拟的, 其速度就肯定比不上物理内存.所以如果想提高速度, 不能认为单纯加大虚拟内存就有用, 最根本的办法是加大物理内存. 因此, 一般推荐 =SWAP 分区大小与内存大小一样=.

选择"逻辑分区-空闲分区起始位置", "用于"选项选择"交换空间".

*** /boot 分区

我们使用 /boot分区 来引导操作系统启动的程序所在的分区. 其大小网上一般推荐 200M, 但我自己使用过程中, 因为系统经常升级, 又没有及时删除不需要的内核, 导致经常提示 /boot 空间不足, 所以这边我分配了 =400M=.

选择 "主分区-空闲分区起始位置-用于:Ext4日志文件系统-挂载点:/boot"

*** / 分区

/ 分区也叫根分区, 在 Linux里, / 是顶层目录, 下面会有 home, usr, tmp 等目录. 我们 =分配 25GB 给根分区=.

选择 "逻辑分区-空闲分区起始位置-用于:Ext4日志文件系统-挂载点:/"

*** /home 分区

与"/ 分区"相同的方法, 把 =剩下的空间= 全部分配给 /home.

*** 安装启动引导器的设备

在划分好分区后, 一定要在"安装启动引导器的设备"这一项中, 选择 /boot 所在分区的名字. 否则系统无法被正确引导.

* /boot空间不足

** 方法一

#+BEGIN_SRC Shell
sudo apt autoremove
#+END_SRC

** 方法二

#+BEGIN_SRC Shell
# 查看磁盘使用情况
df -h

# 查看当前使用内核版本
uname -a

# 查看主机上所有内核版本
sudo apt remove linux-image-
# 按再次Tab键

# 将非当前内核版本删除
sudo apt remove linux-image-4.4.0-31-generic
#+END_SRC

** 方法三

#+BEGIN_SRC Shell
# 查看当前使用内核版本
uname -a

# 查看所有版本
sudo dpkg --get-selections | grep linux

# 把标记install的旧版本都删除
sudo apt autoremove linux-headers-4.10.0-xx linux-image-4.10.0-xx-generic

# linux-headers-4.10.0-xx-generic 会被顺带删除
# linux-image-extra-4.10.0-xx-generic 会被顺带删除

# 再次运行
sudo dpkg --get-selections | grep linux

# 如果有标记为deinstall的内核文件, 删除
sudo dpkg -P linux-image-4.10.0-xx-generic
sudo dpkg -P linux-image-extra-4.10.0-xx-generic

# initrd.img-xxx-generic 千万别删
#+END_SRC

如果不小心误删, 可能导致重启后无法正常进入系统.

强制关机, 不选第一项Ubuntu启动, 而是选择下面的其他选项, 然后选个低版本内核启动.

进入系统后, 再 =sudo apt-get upgrade=, initrd.img-xxx-generic会再次出现.
