#+TITLE:       JavaScript教程--导论
#+AUTHOR:      Pinvon
#+EMAIL:       pinvon@Inspiron
#+DATE:        2018-03-13 二
#+URI:         /blog/%y/%m/%d/javascript教程--导论
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        Web
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

* 声明

本系列的笔记来自于: [[http://javascript.ruanyifeng.com/introduction/intro.html][阮一峰老师的JavaScript教程]]

* 什么是JavaScript语言

JavaScript是一种轻量级的脚本语言. 所谓"脚本语言", 是指它不具备开发OS的能力, 而只是用来编写控制其他大型应用程序的"脚本".

JavaScript本身提供的核心语法不多, 只能用来做一些数学和逻辑运算. 它本身不提供任何与I/O相关的API, 都要靠宿主环境提供, 所以JavaScript只适合嵌入更大型的应用程序环境, 去调用宿主环境提供的API. 最常见的环境就是浏览器和服务器环境(Node项目).

JavaScript的核心语法包括基本的语法构造和标准库(一系列具有各种功能的对象, 如Array, Date, Math等). 除此之外, 各种宿主环境提供额外的API给JavaScript调用. 

如果宿主环境是浏览器, 则提供的API可以分成三大类:
- 浏览器控制类: 操作浏览器
- DOM类: 操作网页的各种元素
- Web类: 实现互联网的各种功能

如果宿主环境是服务器, 则可以提供OS的各种API, 如文件操作API, 网络通信API等, 这些都可在Node环境中找到.

* 为什么学习JavaScript

** 操控浏览器的能力

JavaScript 的发明目的, 就是作为浏览器的内置脚本语言, 为网页开发者提供操控浏览器的能力. 它是目前唯一一种通用的浏览器脚本语言, 所有浏览器都支持. 它可以让网页呈现各种特殊效果, 为用户提供良好的互动体验.

** 广泛的使用领域

Node项目使得JavaScript可以用于开发服务端的大型项目, 网站的前后端都用JavaScript开发已经成为了现实.

可以对数据库进行操作.

可以跨移动平台进行开发(如React Native).

有些OS支持使用JavaScript开发桌面应用程序, 如Chrome App项目, Electron项目, 等.

总之, 它可以让我们只用一种语言, 就开发出适应不同平台的程序.

* 开发环境

打开Chrome浏览器, 按F12, 选择Console, 就可以输入JavaScript, 回车就能看到结果.
