#+TITLE:       编写第一个Fabric应用
#+AUTHOR:      Pinvon
#+EMAIL:       pinvon@Inspiron
#+DATE:        2018-03-27 二
#+URI:         /blog/%y/%m/%d/编写第一个fabric应用
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        BlockChain
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

* 概述

区块链网络应用程序, 首先要给用户提供查询账本(包含特定记录)及更新账本(添加记录)的功能.

** 启动区块链网络

在这个网络中, 需要一些最基本的组件来查询和更新账本.

*** Hyperledger Fabric组件

**** Peer

Fabric网络中的节点(Peer), 表现为一个运行着的Docker容器. Peer可分两种:

***** endorsing peer/endoser

 安装和执行chaincode等一系列操作都离不开peer, 通常会说: chaincode安装在某个peer上. channel内同一个chaincode可以安装到多个peer上, 但只能实例化一次.

***** anchor peer

 锚节点是一个channel或org的代表, 它从orderer获取信息, 并在组内广播给其他peer, 其他peer可以不直接跟orderer打交道.

**** Org

Org由若干个Peer组成. 可在 =crypto-config.yaml= 中设置一个Block中的Peer数量.

**** Channel

Channel有点像"子网", 可以作为两个或多个特定网络成员间的专门以机密交易为目的而建立的. 一个Channel可包含多个Org. 每个Channel拥有一个账本, 并共享给内部的Peer.

同一个Channel内的Org可部署到多台机器上. Fabric为Channel间数据通信和同步提供了多套解决方案, 如基于Zookeeper的Kafka.

*** 交易流程

了解了一些组件之后, 介绍一下交易流程.

**** Client发起交易

Client把交易的相关信息发给Endorser. Endorser的选择有范围限制, 不是随意选择的, 由Chaincode和该Chaincode定义的Endorsement Policy共同决定. 

提交的信息包含:
- ClientID
- ChaincodeID: 该交易所属的Chaincode的ID
- txPayload: 交易本体的信息
- timestamp
- clientSig: Client的签名

**** Endorser接收信息

收到信息后, 首先用Client的公钥验证它的签名, 然后开始模拟交易(模拟的意思是还不写入账本), 并核实相关信息(如, 是否是篡改过的信息等), 根据Endorsement Policy选择是否为该交易背书, 然后把结果发回.

**** Client收集信息

提交交易的Client收集各个Endorser返回的信息, 如果有足够的背书信息后, 就说明这个交易通过了Endorsement阶段. 如果没有收集到足够信息, 交易废止, Client可选择重新发起交易.

通过了Endorsement阶段的交易, 会进入共识阶段.

**** 共识阶段

共识算法很多, 目的都是把有效的交易加入新生成的区块, 并通知所有节点, 使它们保持一致.

*** peer节点


