#+TITLE:       IBM区块链
#+AUTHOR:      pinvon
#+EMAIL:       pinvon@ubuntu
#+DATE:        2018-03-25 日
#+URI:         /blog/%y/%m/%d/ibm
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        BlockChain
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

* 区块链技术基础: 分布式账本简介

** 分布式账本

=分布式账本= 是一种在网络成员之间共享, 复制和同步的 =数据库=. 分布式账本记录网络参与者之间的交易, 比如资产或数据的交换.

网络中的参与者根据共识原则来制约和协商对账本中的记录的更新, 没有中间的第三方仲裁机构参与.

分布式账本中的每条记录都有一个时间戳和唯一的密码签名, 这使得账本成为网络中所有交易的可审计历史记录. Hyperledger Fabric区块链是分布式账本技术的一种实现.

** 区块链

=区块链= 是一种防篡改的, 共享的数字化账本, =用于记录公有或私有对等网络中的交易=. 账本分发给网络中的所有成员节点, 在通过哈希密码算法链接的区块的顺序链中, 永久记录网络中对等节点之间发生资产交易的历史记录.

区块链可以充当事实的来源, 而且区块链网络中的成员只能查看与他们相关的交易.

区块链使用共识协议来降低欺诈的风险: 因为想要篡改账本内容, 需要同时在所有的节点上执行, 由于哈希的计算非常耗时, 短时间内修改多个区块几乎不可能实现, 除非他拥有整个网络超过一半的计算能力. 否则, 只篡改少数账本, 以多数账本的内容为准.

哈希加密算法可确保交易输入的任何改动都会计算出一个不同的哈希值, 表明交易输入可能被损坏.

数字签名可确保交易源自发送方(已使用私钥签名), 而不是冒名顶替者.

** 是否需要区块链

要确定我们的用例是否适合区块链, 要回答以下几个问题:
1. 是否涉及业务网络?
2. 是否使用共识性来验证交易?
3. 是否需要审计线索或来源?
4. 交易记录是否必须不可变或防篡改?
5. 争议的解决方法是否会是最终解决方法?

如果第一个问题和其他问题中的至少一个问题的答案为"是", 则适合区块链技术.

要成为合适的解决方案, 区块链必须涉及一个网络, 但该网络可以具有多种形式. 该网络可位于企业之间, 如供应链; 在企业内, 可以使用区块链网络在部门之间共享参考数据, 或者创建审计和合规性网络. 该网络也可存在于个人之间, 比如需要在区块链上存储数据, 数字资产或合约的人.

** Hyperledger

Hyperledger是一个开源的, 协作完成的项目, 旨在完善跨行业区块链技术.

Hyperledger Fabric是一种区块链架构实现. 它使用模块化架构, 使共识服务和成员服务等组件可以即插即用, 保证商业区块链解决方案的机密性, 灾备能力, 灵活性和可扩展性.

** 企业区块链需求

共享的许可制账本: 是仅可附加的记录系统和单一事实来源, 对业务网络的所有参与成员均可见.

共识协议: 是业务网络的所有参与成员都赞同的协议, 可确保仅使用经过网络验证的交易来更新账本.

加密: 可确保交易的防篡改安全性, 身份验证和完整性.

智能合约: 封装在网络上发生的交易的参与者协议条款; 它们存储在区块链中的验证节点上并通过交易触发.

除了这些属性之外, 企业区块链技术还需要支持关键的行业要求, 比如性能, 经过验证的身份, 以及私下和机密的交易. Hyperledger Fabric就是为满足这些需求而设计的, 它还设计了一种可插拔的共识协议, 允许企业为其网络选择最佳算法.
 
